on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install System Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
            
            - name: install Rust Nightly
              uses: dtolnay/rust-toolchain@nightly
                
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install JS Dependencies
              run: npm install -g bun && bun install

            - name: Typecheck
              run: bun typecheck

            - name: Lint
              run: bun lint

            - name: Rust Build Check
              run: cd src-tauri && cargo check
