on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install System Dependencies
              run: sudo apt-get update && sudo apt install libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev

            - name: Install JS Dependencies
              run: npm install -g bun && bun install

            - name: Typecheck
              run: bun typecheck
            
            - name: Lint
              run: bun lint

            - name: Rust Build Check
              run: cd src-tauri && cargo check
            